cul/ldpd-hyacinth

Gemfile
Gemfile.lock
app/models/digital_object/asset.rb
app/models/digital_object/base.rb
app/models/digital_object/file_system.rb
app/models/digital_object/group.rb
app/models/digital_object/item.rb
app/models/digital_object_type.rb
db/seeds.rb
spec/models/digital_object/file_system_spec.rb
spec/models/digital_object_base_spec.rb
spec/models/digital_object_type_spec.rb

@elo2112 is this what you had in mind? If so will add the db migration in another PR.

add a FileSystem DigitalObject::Base subclass, fixes HYACINTH-69

---

.rubocop.yml
app/jobs/export_search_results_to_csv_job.rb
lib/hyacinth/csv/fields/base.rb
lib/hyacinth/csv/fields/dynamic.rb
lib/hyacinth/csv/fields/internal.rb
lib/hyacinth/csv/flatten.rb
spec/jobs/export_search_results_to_csv_job_spec.rb
spec/requests/digital_objects_spec.rb

I'll squash an resubmit if this looks okay.

Evaluate: Hyacinth 51 revisited

---

app/controllers/projects/fieldsets_controller.rb
app/views/digital_object_imports/index.html.erb

Fix path in fieldsets, add row info to DOI listing

---

app/models/concerns/digital_object/xml_datastream_rendering.rb
app/models/digital_object/base.rb
spec/models/digital_object/base_spec.rb

ticket: HYACINTH-142
AC would like to generate following MODS:
<recordInfo>
<recordCreationDate>
<recordChangeDate>
</recordInfo>

Add DigitalObject created_at and updated_at to XML datastream rendering

---

app/assets/javascripts/digital_objects_app/models/digital_object/base.js
app/assets/templates/digital_objects_app/widgets/digital_object_editor/_header.ejs

When viewing an item, the creator and date created is available for
display, as well as the last user who modified the item and the
modification date.
By the default, the above info is collapsed using
Bootstrap's collapse and data-toggle.

Display create and modify dates, as well as user information

---

lib/hyacinth/ezid/api_session.rb
lib/hyacinth/ezid/server_response.rb
spec/unit/hyacinth/ezid/api_session_spec.rb
spec/unit/hyacinth/ezid/server_response_spec.rb

Code copied from hypatia and modified, with modifications kept at a minimum. Rspec tests were added.

Add EZID API classes

---

app/assets/javascripts/digital_objects_app/widgets/authorized_term_selector.js
app/assets/javascripts/digital_objects_app/widgets/digital_object_editor.js
app/assets/stylesheets/digital_objects/digital_objects.scss
app/assets/templates/digital_objects_app/widgets/digital_object_editor/_dynamic_field.ejs
app/assets/templates/digital_objects_app/widgets/digital_object_editor/_header.ejs

As of Thu Apr 27 10:10:38 EDT 2017, for a limited time only, this branch is running on hyacinth_test.

Display URIs in edit window using checkbox

---

.gitignore
Gemfile
Gemfile.lock
app/models/concerns/digital_object/index_and_search/facet_data.rb
app/models/concerns/digital_object/index_and_search/index.rb
app/models/concerns/digital_object/index_and_search/solr_params.rb
app/models/concerns/digital_object/publishing.rb
app/models/concerns/digital_object/validation.rb
app/models/digital_object/publish_target.rb
spec/models/digital_object/base_spec.rb

- Added byebug
- Can facet by publish target name and [None] (if item is not published)
- HYACINTH-197 #resolve

Published Target Facet

---

app/models/concerns/digital_object/persistence.rb
app/models/concerns/digital_object/publishing.rb
app/models/digital_object/publish_target.rb
spec/models/digital_object/base_spec.rb

Minting DOI before publishing an object. Updating DOI after request from publish target returns.

Minting DOI before publish

---

Gemfile
app/models/concerns/digital_object/xml_datastream_rendering.rb
spec/fixtures/models/concerns/digital_object/test_dynamic_field_data.json
spec/models/concerns/digital_object/xml_datastream_rendering_spec.rb

- Small fixes to xml generation code and a little clean up
- Test for the overall creation of a basic xml document
- Unit test for methods used within the larger recursive method

Tests for XML Generation

---

README.md

I had to reset the origin when I cloned it with https. It kept asking for my username and password. This might be how my git configuration it set up though. Do you remember having this problem?

Cloning with SSH

---

app/controllers/api/v1/projects_controller.rb
app/models/project.rb
config/routes.rb
db/migrate/20190318141027_add_project_url_to_projects.rb
db/schema.rb
spec/factories/projects.rb
spec/models/project_spec.rb
spec/requests/api/v1/projects_spec.rb

- Basic API to CRUD projects
- This endpoint does not contain authorization yet

Project Core API

---

.rubocop.yml
app/controllers/api/v1/projects/enabled_dynamic_fields_controller.rb
app/controllers/api/v1/projects/field_sets_controller.rb
app/controllers/api/v1/projects/publish_targets_controller.rb
app/models/dynamic_field.rb
app/models/enabled_dynamic_field.rb
app/models/field_set.rb
app/models/project.rb
config/routes.rb
db/migrate/20190401182811_create_enabled_dynamic_fields.rb
db/migrate/20190403164437_create_field_sets.rb
db/schema.rb
spec/factories/enabled_dynamic_fields.rb
spec/factories/field_sets.rb
spec/models/enabled_dynamic_field_spec.rb
spec/models/field_set_spec.rb
spec/requests/api/v1/projects/enabled_dynamic_fields_spec.rb
spec/requests/api/v1/projects/field_sets_spec.rb
spec/requests/api/v1/projects/publish_targets_spec.rb

- Adding db migrations and models for enabled dynamic fields and field sets
- Adding tests for both

enabled dynamic fields & field sets

---

app/controllers/api/v1/dynamic_field_groups_controller.rb
app/controllers/api/v1/field_export_profiles_controller.rb
app/models/concerns/field_export/translation_logic.rb
app/models/dynamic_field_group.rb
app/models/export_rule.rb
app/models/field_export_profile.rb
config/routes.rb
db/migrate/20190404201812_create_field_export_rules.rb
db/migrate/20190408195208_add_unique_index_to_export_rules.rb
db/schema.rb
spec/factories/export_rules.rb
spec/factories/field_export_profiles.rb
spec/models/dynamic_field_group_spec.rb
spec/models/export_rule_spec.rb
spec/models/field_export_profile_spec.rb
spec/requests/api/v1/dynamic_field_groups_spec.rb
spec/requests/api/v1/field_export_profiles_spec.rb

- Adding models for export_rules and field_export_profiles, updated relationships between new models and current models
- Added CRUD functionality for field_export_profiles
- Allowing export_rules to be added to dynamic_field_groups

field_export_profiles & export_rules

---

app/controllers/api/v1/groups_controller.rb
app/controllers/api/v1/projects/enabled_dynamic_fields_controller.rb
app/controllers/api/v1/projects/field_sets_controller.rb
app/controllers/api/v1/projects/publish_targets_controller.rb
app/controllers/api/v1/vocabularies/custom_fields_controller.rb
app/controllers/api/v1/vocabularies/terms_controller.rb
app/controllers/api/v1/vocabularies_controller.rb
app/controllers/application_api_controller.rb
app/models/ability.rb
app/models/permission.rb
app/models/user.rb
spec/factories/groups.rb
spec/factories/users.rb
spec/models/ability_spec.rb
spec/requests/api/v1/projects/enabled_dynamic_fields_spec.rb
spec/requests/api/v1/projects/field_sets_spec.rb
spec/requests/api/v1/projects/publish_targets_spec.rb
spec/support/authenticate_user.rb
spec/support/authorization.rb

- Changing to using CanCanCan DSL to assign permissions in ability
- Updating tests for project sub controllers
- Using symbols to check for authorization when controllers don't have a model backing it
Disclaimer: This could probably use more granular testing, but I can't look at it anymore. Thought I would pass it on to you guys to get your thoughts.

Project Permissions

---

app/controllers/api/v1/digital_objects_controller.rb
app/controllers/application_api_controller.rb
app/models/ability.rb
app/models/concerns/digital_object_concerns/serialization.rb
app/models/digital_object/base.rb
spec/factories/digital_objects/test_subclasses.rb
spec/factories/projects.rb
spec/models/ability_spec.rb
spec/requests/api/v1/digital_objects_spec.rb
spec/support/authenticate_user.rb

begin authorizing digital_objects_controller

implement Ability logic for digital object permissions in projects

---

app/controllers/api/v1/digital_objects_controller.rb
app/models/concerns/digital_object_concerns/digital_object_data/setters/projects.rb
config/initializers/00_hyacinth.rb
config/routes.rb
config/templates/hyacinth.template.yml
lib/hyacinth/adapters/publication_adapter/development.rb
spec/factories/projects.rb
spec/models/concerns/digital_object_concerns/digital_object_data/setters/projects_spec.rb

- Fixing DigitalObject#create action
- Adding development publication adapter
- Fixing setter for projects
- Adding /preserve route for digital objects

Digital Object Api Fixes

---

app/controllers/api/v1/digital_objects_controller.rb
app/graphql/types/digital_object/asset_type.rb
app/graphql/types/digital_object/item_type.rb
app/graphql/types/digital_object/publish_entry_type.rb
app/graphql/types/digital_object/site_type.rb
app/graphql/types/digital_object/structured_children_type.rb
app/graphql/types/digital_object_interface.rb
app/graphql/types/publish_entry_type.rb
app/graphql/types/query_type.rb
app/models/ability.rb
app/models/digital_object/base.rb
spec/factories/digital_objects/items.rb
spec/factories/digital_objects/test_subclasses.rb
spec/models/digital_object/base_spec.rb
spec/requests/graphql/query/digital_object_spec.rb

This is just the beginnings of the graphql implementation for digital object.

Using graphql to query for a singular digital object

---

app/javascript/hyacinth_ui_v1/components/projects/enabled_dynamic_fields/EnabledDynamicFieldEdit.js
app/javascript/hyacinth_ui_v1/components/projects/enabled_dynamic_fields/EnabledDynamicFieldShow.js

I am duplication code here, but this is just temporary until we can move the enabled fields queries over to graphql

Temporary fix to enabled fields ui

---

app/javascript/hyacinth_ui_v1/components/digital_objects/system_data/SystemData.js

Temporary fix until we can move the comoponent over to graphql

Displaying createdBy and updateBy uids 

---

.rubocop_todo.yml
.travis.yml
app/javascript/hyacinth_ui_v1/components/digital_objects/digitalObjectInterface.js
app/javascript/hyacinth_ui_v1/components/digital_objects/metadata/MetadataShow.js
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/ItemRightsForm.js
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/Rights.js
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/RightsShow.js
app/javascript/hyacinth_ui_v1/components/layout/forms/SubmitButton.js
app/javascript/hyacinth_ui_v1/components/ui/forms/buttons/SubmitButton.js
app/javascript/hyacinth_ui_v1/components/ui/forms/inputs/BooleanRadioButtons.js
app/javascript/hyacinth_ui_v1/components/ui/forms/inputs/ReadOnlyInput.js
app/javascript/hyacinth_ui_v1/components/ui/forms/inputs/TextInputWithAddAndRemove.js
app/models/concerns/digital_object_concerns/digital_object_data/setters.rb
app/models/concerns/digital_object_concerns/digital_object_data/setters/rights.rb
app/models/digital_object/base.rb
package.json
spec/models/concerns/digital_object_concerns/digital_object_data/setters_spec.rb
spec/models/digital_object/base_spec.rb
yarn.lock

@cgalarza It would be great to get your thoughts on this when you have a chance.  I wanted to make sure that I implemented things in a way that aligns with your other digitalObjectInterface-related views, and that my fixes for react warnings didn't work against any of your preferences.  Thanks!

Rights data serialization

---

app/controllers/api/v1/digital_objects/rights_controller.rb
app/controllers/api/v1/digital_objects_controller.rb
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/ItemRightsForm.js
app/javascript/hyacinth_ui_v1/util/hyacinth_api.js
app/models/ability.rb
app/models/digital_object/base.rb
app/models/permission.rb
config/routes.rb
spec/models/ability_spec.rb
spec/requests/api/v1/digital_objects/rights_spec.rb

Enforce distinct project permission for rights updates via REST API

Hyacinth 351

---

app/javascript/hyacinth_ui_v1/components/ui/forms/inputs/ControlledVocabularyMenu.js
yarn.lock

Fixing some immediate problems with the controlled vocabularies dropdown. I want to get this commits into master in case it takes me longer than expected to add the ability to create a new term.

Fix controlled vocabulary select

---

app/controllers/api/v1/projects/enabled_dynamic_fields_controller.rb
app/javascript/hyacinth_ui_v1/components/projects/enabled_dynamic_fields/EnabledDynamicFieldForm.js
app/models/concerns/digital_object_concerns/validations.rb
app/models/enabled_dynamic_field.rb
app/validators/digital_object/projects_validator.rb
app/validators/digital_object/restrictions_validator.rb
app/validators/digital_object/type_validator.rb
app/validators/enabled_dynamic_field/open_to_all_projects_validator.rb
db/migrate/20200102155446_add_open_to_all_projects_to_enabled_dynamic_fields.rb
db/schema.rb
spec/factories/enabled_dynamic_fields.rb
spec/requests/api/v1/projects/enabled_dynamic_fields_spec.rb

* Organize validator classes into modules where appropriate
* Add a switch to limit dynamic field enabled to primary project (HYACINTH-389)
* Add cancel button to bottom of Project Enabled Dynamic Fields form (HYACINTH-441)

HYACINTH-389 and HYACINTH-441

---

app/graphql/types/rule_type.rb
app/models/ability.rb
spec/models/ability_spec.rb
spec/requests/graphql/query/authenticated_user_spec.rb

- Adding test for Ability#to_list and authenticatedUser graphql request
- Converting all the keys within the conditions hash to camelCase as part before returning via graphql

Ability#to_list

---

.rubocop_todo.yml
Gemfile
Gemfile.lock
app/controllers/concerns/hyacinth/users/cas_authentication_behavior.rb
spec/rails_helper.rb
spec/requests/logging_in.rb

Addresses HYACINTH-450, HYACINTH-449 and HYACINTH-455.
(Preferably, these test would get merged in before I write tests for #187)

User login tests

---

app/javascript/hyacinth_ui_v1/components/ProtectedRoute.js
app/javascript/hyacinth_ui_v1/components/projects/core_data/CoreData.js
app/javascript/hyacinth_ui_v1/components/projects/enabled_dynamic_fields/EnabledDynamicFieldShow.js
app/javascript/hyacinth_ui_v1/components/projects/enabled_dynamic_fields/EnabledDynamicFields.js
app/javascript/hyacinth_ui_v1/components/projects/field_sets/FieldSet.js
app/javascript/hyacinth_ui_v1/components/projects/field_sets/FieldSetIndex.js
app/javascript/hyacinth_ui_v1/components/projects/permissions/Permissions.js
app/javascript/hyacinth_ui_v1/components/projects/publish_targets/PublishTarget.js
app/javascript/hyacinth_ui_v1/components/projects/publish_targets/PublishTargetIndex.js

- Making sure we are checking read permissions for all readonly pages in the Projects Interface
- Fixing various incorrect permissions checks on the UI

Ensuring Permissions are Checked for all Project Pages

---

app/javascript/hyacinth_ui_v1/components/digital_objects/metadata/MetadataShow.js
app/javascript/hyacinth_ui_v1/components/ui/forms/inputs/TermSelect.js

This is just a temporary solution in order to get the rights form and metadata form working properly.

Using pref_label instead of prefLabel when displaying controlled terms in digital objects ui

---

app/models/project.rb
db/migrate/20200127180724_add_has_asset_rights_to_projects.rb
db/schema.rb
spec/requests/api/v1/projects_spec.rb

This PR contains just the new flag on for projects. Also, I have no preference concerning the column name (has_asset_rights) and will accept any majority-agreed-upon name change.

Add flag to project for asset rights

---

app/graphql/types/project_type.rb
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/RightsEdit.js
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/rights_form/AssetRightsForm.js
app/javascript/hyacinth_ui_v1/graphql/digitalObjects.js
spec/factories/digital_objects/test_subclasses.rb
spec/factories/projects.rb
spec/requests/api/v1/digital_objects/rights_spec.rb
spec/requests/api/v1/projects_spec.rb
spec/requests/graphql/query/digital_object_spec.rb

add the asset rights flag to project graphql type to drive conditional display of asset rights form
part of HYACINTH-336

Hyacinth 482

---

app/graphql/mutations/create_project.rb
app/graphql/mutations/update_project.rb
app/javascript/hyacinth_ui_v1/components/projects/ProjectIndex.js
app/javascript/hyacinth_ui_v1/components/projects/ProjectNew.js
app/javascript/hyacinth_ui_v1/components/projects/core_data/CoreDataEdit.js
app/javascript/hyacinth_ui_v1/components/projects/core_data/CoreDataShow.js
app/javascript/hyacinth_ui_v1/graphql/projects.js
spec/requests/graphql/mutations/create_project_spec.rb
spec/requests/graphql/mutations/update_project_spec.rb
spec/requests/graphql/query/project_spec.rb
spec/requests/graphql/query/projects_spec.rb
spec/support/graphql_helper.rb

UI for updating/displaying the asset-rights flag (HYACINTH-339)

Hyacinth 336 fcd1

---

app/graphql/mutations/create_project.rb
app/graphql/mutations/update_project.rb
app/graphql/types/project_type.rb
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/RightsEdit.js
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/rights_form/AssetRightsForm.js
app/javascript/hyacinth_ui_v1/components/projects/ProjectIndex.js
app/javascript/hyacinth_ui_v1/components/projects/ProjectNew.js
app/javascript/hyacinth_ui_v1/components/projects/core_data/CoreDataEdit.js
app/javascript/hyacinth_ui_v1/components/projects/core_data/CoreDataShow.js
app/javascript/hyacinth_ui_v1/graphql/digitalObjects.js
app/javascript/hyacinth_ui_v1/graphql/projects.js
app/models/concerns/digital_object_concerns/assets/validations.rb
app/models/project.rb
db/migrate/20200127180724_add_has_asset_rights_to_projects.rb
db/schema.rb
spec/factories/digital_objects/items.rb
spec/factories/digital_objects/test_subclasses.rb
spec/factories/projects.rb
spec/models/project_spec.rb
spec/requests/api/v1/digital_objects/rights_spec.rb
spec/requests/api/v1/projects_spec.rb
spec/requests/graphql/mutations/create_project_spec.rb
spec/requests/graphql/mutations/digital_object/update_asset_rights_mutation_spec.rb
spec/requests/graphql/mutations/update_project_spec.rb
spec/requests/graphql/query/digital_object_spec.rb
spec/requests/graphql/query/project_spec.rb
spec/requests/graphql/query/projects_spec.rb
spec/support/graphql_helper.rb

UI refinements for assets
UI for maintaining Project flag to enable asset rights
Validations for asset rights assignments

Asset Rights entry enabled (fixes HYACINTH-336)

---

.rubocop_todo.yml
app/controllers/api/v1/digital_objects/resources_controller.rb
app/graphql/mutations/create_asset.rb
app/graphql/types/digital_object_interface.rb
app/graphql/types/resource_type.rb
app/javascript/hyacinth_ui_v1/components/digital_objects/DigitalObject.js
app/javascript/hyacinth_ui_v1/components/digital_objects/DigitalObjectInterface.js
app/javascript/hyacinth_ui_v1/components/digital_objects/asset_data/AssetData.js
app/javascript/hyacinth_ui_v1/graphql/digitalObjects.js
app/javascript/hyacinth_ui_v1/util/FontAwesome.js
app/models/concerns/digital_object_concerns/serialization.rb
config/environments/development.rb
config/initializers/devise.rb
config/routes.rb
config/templates/hyacinth.template.yml
lib/hyacinth/adapters/lock_adapter/abstract.rb
lib/hyacinth/adapters/lock_adapter/database_entry_lock.rb
lib/hyacinth/adapters/storage_adapter/abstract.rb
lib/hyacinth/adapters/storage_adapter/disk.rb
lib/hyacinth/adapters/storage_adapter/memory.rb
lib/hyacinth/digital_object/resource.rb
lib/hyacinth/exceptions.rb
lib/hyacinth/storage/abstract_storage.rb
spec/factories/digital_objects/test_subclasses.rb
spec/fixtures/files/test.txt
spec/hyacinth/adapters/lock_adapter/database_entry_lock_spec.rb
spec/requests/api/v1/digital_objects/resources_spec.rb
spec/requests/graphql/mutations/create_asset_spec.rb
spec/shared_examples/lock_adapter/shared_examples.rb

Also update Mutations::CreateAsset to assign master filename to Asset title during creation.

HYACINTH-480: Add asset download feature

---

app/models/concerns/digital_object/assets/file_import.rb
app/models/concerns/digital_object/fedora.rb
app/models/digital_object/asset.rb
lib/hyacinth/utils/path_utils.rb
lib/tasks/hyacinth/captions.rake

When captions content has changed
And the new content is pushed to Fedora
Copy the new content to the wowza companion file in the access directory

2.x companion files

---

app/graphql/mutations/batch_export/create_batch_export.rb
app/graphql/types/extensions/solr_search.rb
app/graphql/types/query_type.rb
app/graphql/types/search_attributes.rb
app/graphql/types/vocabulary_type.rb
app/javascript/hyacinth_v1/App.js
app/javascript/hyacinth_v1/components/digital_objects/DigitalObjectFacets.js
app/javascript/hyacinth_v1/components/digital_objects/DigitalObjectSearch.js
app/javascript/hyacinth_v1/graphql/digitalObjects.js
app/javascript/hyacinth_v1/utils/filterArrayParam.js
lib/hyacinth/adapters/digital_object_search_adapter/solr.rb
package.json
spec/fixtures/solr_cores/hyacinth-solr-6-3/conf/solrconfig.xml
spec/requests/graphql/mutations/batch_export/create_batch_export_spec.rb
spec/requests/graphql/query/terms_spec.rb
yarn.lock

- import Card in DigitalObjectSearch to handle empty result set

digital object type facet is functional (HYACINTH-492)

---

app/javascript/hyacinth_v1/components/digital_objects/DigitalObjectSearch.js
app/javascript/hyacinth_v1/components/digital_objects/search/QueryForm.js
lib/solr/params.rb

Stacking a one-box form on top of the facet navs

rudimentary keyword search

---

app/graphql/enums/batch_import_priority_enum.rb
app/graphql/enums/batch_import_status_enum.rb
app/graphql/enums/digital_object_import_status_enum.rb
app/graphql/hyacinth_schema.rb
app/graphql/types/batch_export_type.rb
app/graphql/types/batch_import_type.rb
app/graphql/types/digital_object_import_type.rb
app/graphql/types/query_type.rb
app/models/ability.rb
app/models/batch_import.rb
app/models/digital_object_import.rb
db/migrate/20200219191235_create_batch_import_and_digital_object_import.rb
db/migrate/20200227172812_add_indexes_to_digital_object_import.rb
db/migrate/20200227202735_remove_status_from_batch_import.rb
db/schema.rb
spec/factories/batch_imports.rb
spec/factories/digital_object_imports.rb
spec/models/ability_spec.rb
spec/models/batch_import_spec.rb
spec/models/digital_object_import_spec.rb
spec/requests/graphql/query/authenticated_user_spec.rb
spec/requests/graphql/query/batch_import_spec.rb
spec/requests/graphql/query/batch_imports_spec.rb
spec/requests/graphql/query/digital_object_import_spec.rb
spec/requests/graphql/query/digital_object_imports_spec.rb

Closes HYACINTH-512 and HYACINTH-514

Adding models and graphql endpoint for BatchImport and DigitalObjectImport

---

app/javascript/hyacinth_v1/components/dynamic_fields/DynamicFieldForm.js
spec/requests/graphql/mutations/update_dynamic_field_spec.rb

This is a very minor PR, but I wanted to make sure that we are consistently using the correct format of select options.

Consistent description of the format of select_options

---

app/controllers/api/v1/downloads_controller.rb
config/routes.rb

This is in preparation for adding a batch_imports download endpoint. For which we have to provide a download to the original file and a file without the successful rows.

Refactoring downloads controller

---

app/javascript/hyacinth_v1/components/dynamic_fields/DynamicFieldForm.js
app/models/dynamic_field.rb
spec/models/dynamic_field_spec.rb

Dynamic Fields that are defined as textarea cannot be facetable.
HYACINTH-517

is_facetable cannot be set to true for textareas

---

spec/graphql/types/extensions/solr_search_spec.rb
spec/hyacinth/digital_object/facets_spec.rb
spec/hyacinth/digital_object/solr_keys_spec.rb

- spec Hyacinth::DigitalObject::Facets
- spec Hyacinth::DigitalObject::SolrKeys

add specs for Solr field name generators

---

.rubocop_todo.yml
app/graphql/types/digital_object/search_record.rb
app/graphql/types/extensions/map_to_digital_object_search_record.rb
app/graphql/types/query_type.rb
config/templates/hyacinth.template.yml
spec/graphql/types/extensions/map_to_digital_object_search_record_spec.rb

- Updates the DigitalObjects query result type name
- Fixes a typo in hyacinth.template.yml

HYACINTH-590

---

app/graphql/enums/facet_values/order_fields_enum.rb
app/graphql/enums/filter_match_enum.rb
app/graphql/enums/search_type_enum.rb
app/graphql/inputs/facet_values/order_by_input.rb
app/graphql/types/facets/value_type_results.rb
app/graphql/types/filter_attributes.rb
app/graphql/types/query_type.rb
app/graphql/types/search_attributes.rb
app/graphql/types/vocabulary_type.rb
app/javascript/hyacinth_v1/components/digital_objects/DigitalObjectSearch.js
app/javascript/hyacinth_v1/components/digital_objects/search/FacetSidebar.js
app/javascript/hyacinth_v1/components/digital_objects/search/SelectedFacetsBar.js
app/javascript/hyacinth_v1/utils/filterArrayParam.js
lib/hyacinth/adapters/digital_object_search_adapter/solr.rb
lib/hyacinth/adapters/digital_object_search_adapter/solr/document_generator.rb
lib/solr/params.rb
spec/hyacinth/adapters/digital_object_search_adapter/solr_spec.rb
spec/requests/graphql/mutations/batch_export/create_batch_export_spec.rb
spec/requests/graphql/query/digital_objects_spec.rb
spec/requests/graphql/query/facet_values_spec.rb
spec/requests/graphql/query/terms_spec.rb
spec/solr/params_spec.rb

Opening a draft PR while I work on HYACINTH-582

Add typeOfSearch to Types::SearchAttributes (HYACINTH-581)

---

app/controllers/api/v1/digital_objects_controller.rb
app/graphql/hyacinth_schema.rb
app/graphql/mutations/digital_object/delete_digital_object.rb
app/graphql/mutations/digital_object/purge_digital_object.rb
app/graphql/types/mutation_type.rb
app/javascript/hyacinth_v1/components/digital_objects/system_data/SystemData.js
app/javascript/hyacinth_v1/components/shared/forms/buttons/PurgeButton.js
app/javascript/hyacinth_v1/graphql/digitalObjects.js
app/models/concerns/digital_object_concerns/find_behavior.rb
spec/requests/api/v1/digital_objects_spec.rb
spec/requests/graphql/mutations/digital_object/delete_digital_object_spec.rb
spec/requests/graphql/mutations/digital_object/purge_digital_object_spec.rb

This PR includes HYACINTH-415, digital object purge mutation.

Hyacinth 622 digital object delete mutation

---

.rubocop_todo.yml
app/graphql/hyacinth_schema.rb
app/graphql/mutations/digital_object/create_digital_object.rb
app/graphql/mutations/digital_object/update_descriptive_metadata.rb
app/graphql/mutations/digital_object/update_rights.rb
spec/graphql/hyacinth_schema_spec.rb
spec/requests/graphql/mutations/digital_object/create_digital_object_spec.rb
spec/requests/graphql/mutations/digital_object/update_descriptive_metadata_mutation_spec.rb
spec/requests/graphql/mutations/digital_object/update_descriptive_metadata_spec.rb
spec/requests/graphql/mutations/digital_object/update_rights_mutation_spec.rb

And HYACINTH-412 because it was also related to error handling.
And HYACINTH-738 because it was related too.

HYACINTH 735

---

spec/factories/digital_objects/items.rb
spec/fixtures/files/batch_import/sample-batch-import-utf8.csv
spec/jobs/batch_export_job_spec.rb
spec/models/batch_import_spec.rb
spec/requests/graphql/mutations/digital_object/create_digital_object_spec.rb
spec/requests/graphql/query/digital_object_spec.rb

- spec graphql query with non-ascii utf8 data
- spec graphql update with non-ascii utf8
- spec batch import from csv with non-ascii utf8 data
- spec batch export of items with non-ascii utf8 data

Verification tests for non-ASCII UTF-8 (HYACINTH-522)

---

app/graphql/types/dynamic_field_group_type.rb
app/graphql/types/dynamic_field_type.rb
app/javascript/src/hyacinth_v1/components/dynamic_fields/DynamicFieldForm.js
app/javascript/src/hyacinth_v1/components/shared/dynamic_fields/DynamicFieldsBreadcrumbs.js
app/javascript/src/hyacinth_v1/graphql/dynamicFieldGroups.js
app/javascript/src/hyacinth_v1/graphql/dynamicFields.js
spec/requests/graphql/query/dynamic_field_group_spec.rb
spec/requests/graphql/query/dynamic_field_spec.rb

Also fixes:
- HYACINTH-837 - Fix DynamicFieldForm.js console warnings

HYACINTH-797 (fix dynamic field breadcrumb display)

---

app/javascript/src/hyacinth_v1/components/controlled_vocabularies/ControlledVocabularyForm.js
app/javascript/src/hyacinth_v1/components/controlled_vocabularies/terms/TermForm.js
app/javascript/src/hyacinth_v1/components/digital_objects/rights/rights_form/AssetRightsForm.js
app/javascript/src/hyacinth_v1/components/digital_objects/rights/rights_form/ItemRightsForm.js
app/javascript/src/hyacinth_v1/components/dynamic_field_categories/DynamicFieldCategoryForm.js
app/javascript/src/hyacinth_v1/components/dynamic_field_groups/DynamicFieldGroupForm.js
app/javascript/src/hyacinth_v1/components/dynamic_fields/DynamicFieldForm.js
app/javascript/src/hyacinth_v1/components/field_export_profiles/FieldExportProfileForm.js
app/javascript/src/hyacinth_v1/components/projects/enabled_dynamic_fields/EnabledDynamicFieldForm.js
app/javascript/src/hyacinth_v1/components/projects/field_sets/FieldSetForm.js
app/javascript/src/hyacinth_v1/components/publish_targets/PublishTargetForm.js
app/javascript/src/hyacinth_v1/components/shared/forms/FormButtons.js
app/javascript/src/hyacinth_v1/components/shared/forms/buttons/DeleteButton.js
app/javascript/src/hyacinth_v1/components/shared/forms/inputs/term_select/TermOptions.js

use SuccessHandler functions to prevent state updates on unloaded components

Hyacinth 852 form buttons history cleanup

---

app/javascript/src/hyacinth_v1/components/digital_objects/DigitalObject.js
app/javascript/src/hyacinth_v1/components/digital_objects/children/ChildStructure.js
app/javascript/src/hyacinth_v1/components/digital_objects/children/ChildStructureEditor.js
app/javascript/src/hyacinth_v1/components/digital_objects/children/Children.js
app/javascript/src/hyacinth_v1/graphql/digitalObjects.js
package.json
yarn.lock

@elohanlon, in the previous version of this PR, you had mentioned encountering a useState error when created a child asset. I wasn't able to reproduce this. Let me know if it crops up again.
However, I am seeing this warning in the console and am wondering if you have any insight into its solution:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
in ProgressButton (at FormButtons.js:26)
in div (created by Col)
in Col (at FormButtons.js:25)
in div (created by Row)
in Row (at FormButtons.js:16)
in div (at FormButtons.js:15)
in FormButtons (at ChildStructure.js:76)
in div (at ChildStructure.js:75)
in div …
```

Hyacinth 473 drag rearrange child objects (new)

---

app/jobs/concerns/resource_request_jobs/derivativo_job_behaviors.rb
app/jobs/concerns/resource_request_jobs/iiif_job_behaviors.rb
app/jobs/resource_requests/access_job.rb
app/jobs/resource_requests/featured_thumbnail_region_job.rb
app/jobs/resource_requests/fulltext_job.rb
app/jobs/resource_requests/iiif_deregistration_job.rb
app/jobs/resource_requests/iiif_registration_job.rb
app/jobs/resource_requests/poster_job.rb
app/models/resource_request.rb
spec/jobs/resource_requests/iiif_deregistration_job_spec.rb
spec/jobs/resource_requests/iiif_registration_job_spec.rb
spec/models/resource_request_spec.rb

@barmintor Here are some proposed changes to your branch!  I'm not sure my renaming suggestions are perfect, but maybe they help a bit?  What do you think?

Proposed changes for HYACINTH-624

---

app/javascript/src/hyacinth_v1/components/digital_objects/rights/rights_form/AssetRightsForm.js
app/models/concerns/digital_object_concerns/assets/validations.rb
config/rights_fields.yml
spec/models/concerns/digital_object_concerns/validations/rights_fields_validation_spec.rb
spec/requests/graphql/mutations/digital_object/update_rights_mutation_spec.rb

see also HYACINTH-871
Deploying this change will require updating the database to change the relevant dynamic field group's string_key

change string key of rights group restriction_on_access to asset_access_restrictions

---

app/javascript/src/hyacinth_v1/MainContent.js
app/javascript/src/hyacinth_v1/components/digital_objects/DigitalObjectList.js
app/javascript/src/hyacinth_v1/components/digital_objects/DigitalObjectSearch.js
app/javascript/src/hyacinth_v1/components/digital_objects/common/DisplayField.js
app/javascript/src/hyacinth_v1/components/digital_objects/search/FacetSidebar.js
app/javascript/src/hyacinth_v1/components/digital_objects/search/QueryForm.js
app/javascript/src/hyacinth_v1/components/shared/forms/inputs/PlainText.js
spec/features/ui/v1/digital_objects/metadata/edit_spec.rb
spec/features/ui/v1/digital_objects/metadata/show_spec.rb
spec/features/ui/v1/digital_objects_spec.rb
spec/rails_helper.rb

HYACINTH-934 (Search button should always forces result refresh)
HYACINTH-937 (Add a clear search button that clears search parameters)
HYACINTH-936 (DisplayField component should show new lines and other text spacing)

HYACINTH-934, HYACINTH-937, and HYACINTH-936

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/graphql_controller.rb
app/graphql/mutations/switch_to_user.rb
app/graphql/types/mutation_type.rb
app/javascript/src/hyacinth_v1/components/users/SwitchToUserButton.js
app/javascript/src/hyacinth_v1/components/users/UserEdit.js
app/javascript/src/hyacinth_v1/graphql/users.js
spec/features/ui/v1/users_spec.rb
spec/requests/graphql/mutations/switch_to_user_spec.rb

(useful for troubleshooting issues as that user)

HYACINTH-444: Add ability for an admin to log in as another user

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/00_hyacinth.rb
config/initializers/cookies_serializer.rb
config/initializers/zeitwerk.rb
lib/hyacinth/utils/solr_utils.rb
spec/factories/controlled_vocabulary.rb
spec/factories/user.rb
spec/models/concerns/digital_object/uri_service_values_spec.rb
spec/rails_helper.rb
spec/support/valid_user_request_helper.rb

and some zeitwerk-friendly module renames

use a cul_hydra ref with no blacklight dependency

---

lib/tasks/hyacinth/users.rake

add rake tasks to reset all user credentials from command line or assign individually
- UNIX-9927

add rake tasks to reset all user credentials
