app/jobs/process_digital_object_import_job.rb
db/migrate/20151223174138_add_requeue_count_to_digital_object_imports.rb
db/schema.rb
spec/jobs/process_digital_object_import_job_spec.rb
spec/models/digital_object_import_spec.rb

The parent of a Digital Object can be specified at the time of import.
However, if the specified parent is not found, the Digital Object
cannot be imported. However, it is possible that the parent Digital
Object is in the queue, ready to be imported, but has not yet been
processed. Therefore, the child Digital Object will be re-queued,
thus allowing the parent Digital Object to be processed before the
re-queued child Digital Object.
Digital Objects can be re-queued at most MAX_REQUEUES=3 times
Note that DigitalObjectImport instances are used to represent the
Digital Objects waiting to be imported.

Re-queue DigitalObjectImport if given parent is not found

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb
spec/models/digital_object/file_system_spec.rb
spec/spec_helper.rb

require_project_permission! now accepts an array of permissions
and provides AND, OR logic
Specs for new code uses a partial double, and config changes
were made to spec_helper.rb to catch calls to unimplemented
methods. An existing spec with such a call was updated.

Add AND, OR functionality to permission check

---

app/assets/templates/digital_objects_app/digital_objects/manage_children.ejs
app/assets/templates/digital_objects_app/digital_objects/show.ejs
app/assets/templates/digital_objects_app/widgets/digital_object_ordered_child_editor/index.ejs

The following menus show up when a user with read-only permission on a project is viewing an Item:
-) Manage Child Assets
-) New Child Asset
-) Manage Parents
These menus should be hidden if the user does not have the proper permissions.

Hyacinth 152 - Hide menus based on permissions when viewing an item

---

app/models/project.rb

In a project, for any of the Digital Object Types, if any field is enabled, then the Title Sort Portion field should automatically become Enabled and Required, and the Title Non-Sort Portion field should become Enabled.
The above functionality was broken. Also, when an existing line of code was moved to its correct position, a new symptom (infinite calls to ensure_that_title_fields_are_enabled_and_required) appeared. Fix: Database query code was changed back to the previous version.

Fix "Title Sort Portion" Enabled/Required functionality

---

lib/hyacinth/ezid/hyacinth_metadata_retrieval.rb
spec/fixtures/lib/hyacinth/ezid/ezid_item.json
spec/unit/hyacinth/ezid/hyacinth_metadata_retrieval_spec.rb

This adds a level of abstraction between the internal format used
by hyacinth and the ezid code, thus insulating the ezid code from
possible future changes to the internal format of the metadata.
Also, it adds filtering; the predominant case is where ezid only
wants one value from a multi-value field. In most of these cases,
we just return the first value. We also need to filter the names
by role.

Add functionality to retrieve metadata from Digital Object

---

lib/hyacinth/ezid/datacite_metadata_builder.rb
lib/hyacinth/ezid/doi.rb
spec/fixtures/lib/hyacinth/ezid/datacite.xml
spec/unit/hyacinth/ezid/datacite_metadata_builder_spec.rb

This pull request contains the following:
- Code that will generate the datacite (http://schema.datacite.org) xml file used to push metadata to the EZID server.
- The Doi class, which encapsulates a few data members. Since there is no functionality besides attribute readers, there is no associated spec file for this class.
The branch represented by this pull request was successfully cap deploy'ed to the dev instance.

Add functionality to create datacite metadata; Add doi class.

---

lib/tasks/hyacinth/setup.rake

Simple change: just changed the hash key to the official EZID test shoulder from 'shoulder' to 'test_shoulder'. Matches 'test_user' and 'test_password'.

Specify test shoulder in development/test ezid.yml

---

lib/hyacinth/ezid/datacite_metadata_builder.rb
spec/fixtures/lib/hyacinth/ezid/datacite.xml

The valid values for resourceType are specified in a datacite
vocabulary, which does not match the values in our vocabulary.
Since resourceType is not a required element, skip it.
In the future, we can try to come up with a mapping. However, this
mapping would have to be updated when we add new entries in our
vocabulary.

Do not include the resourceType in the datacite xml

---

app/models/user.rb
spec/models/user_spec.rb

This is to clarify the otherwise confusing server error when metadata editors look at the controlled_vocabularies index view.

short circuit to false if checking basic editor permissions on a nil controlled vocabulary

---

app/assets/javascripts/digital_objects_app/controllers/digital_objects_controller.js
app/models/concerns/digital_object/persistence.rb
app/models/concerns/digital_object/publishing.rb
spec/models/concerns/digital_object/publishing_spec.rb
spec/models/digital_object/file_system_spec.rb

Unpublishing from all publish targets when an item is deleted.
I am not sure the tests I added are helpful, but it helped me understand the logic better. I have a feeling that I may be missing something else that needs to happen as part of this process. @elohanlon, let me know if you can think of anything. Should we add something to the delete dialog that says something along the lines of "Deleting this object unpublishes it from all publish targets"?

Unpublish on delete, HYACINTH-186

---

app/assets/javascripts/digital_objects_app/models/digital_object/base.js
app/assets/templates/digital_objects_app/widgets/digital_object_editor/_header.ejs
app/jobs/export_search_results_to_csv_job.rb
app/models/concerns/digital_object/digital_object_record.rb
app/models/concerns/digital_object/persistence.rb
app/models/concerns/digital_object/publishing.rb
app/models/concerns/digital_object/serialization.rb
app/models/digital_object/asset.rb
app/models/digital_object/base.rb
db/migrate/20180122214510_add_first_published_at_to_digital_object_records.rb
db/schema.rb
spec/models/digital_object/base_spec.rb

- Added first_published_at field to dynamic object record
- Added to serialization methods
- Displaying field in GUI
- Field can be set via CSV import
- first_published_at date is set when object is first published to its primary target
MISSING: Adding first_published_at to MODS serialization. We'll need to do more research on this, but should move forward with this code, so we can start populating the field.

Adding first_published_at. HYACINTH-196

---

app/models/digital_object/base.rb

During a csv import resetting parent relationships by deleting the relationships in the fedora object and overriding them with the relationships provided in the CSV.

Resetting parent relationships in CSV import

---

lib/hyacinth/xml_generator/element.rb
spec/lib/hyacinth/xml_generator_spec.rb

This prevents a bug where we end up interpolating a string.

Converting 'content' key to an array and creating a hash out of every value

---

app/controllers/api/v1/projects/publish_targets_controller.rb
app/models/publish_target.rb
config/routes.rb
db/migrate/20190319163208_require_columns_to_publish_targets.rb
db/schema.rb
spec/factories/publish_targets.rb
spec/models/publish_target_spec.rb
spec/requests/api/v1/projects/publish_targets_spec.rb

Basic endpoint to CRUD a publish target. 
Note:
- This does not include permissions.
- This also does not include priority of publish target

Publish Targets API

---

app/javascript/hyacinth_ui_v1/components/controlled_vocabularies/ControlledVocabularies.js
app/javascript/hyacinth_ui_v1/components/controlled_vocabularies/terms/Terms.js
app/javascript/hyacinth_ui_v1/components/dynamic_fields/DynamicFields.js
app/javascript/hyacinth_ui_v1/components/field_export_profiles/FieldExportProfiles.js
app/javascript/hyacinth_ui_v1/components/projects/core_data/CoreDataShow.js
app/javascript/hyacinth_ui_v1/components/users/UserEdit.js
app/models/ability.rb
spec/requests/api/v1/dynamic_field_categories_spec.rb

We shouldn't use :index, :show, :edit and :new to define permissions. These actions are mapped to one of :read, :update, :create and are really only used for RESTful responses. Once we move everything to graphql we shouldn't need to use them anymore.

No longer using :index, :show, :edit and :new to define permissions

---

lib/hyacinth/xml_generator/element.rb
spec/hyacinth/xml_generator/element_spec.rb

@barmintor Same changes as Hyacinth 2, with minor modifications to follow Hyacinth 3 conventions.

Allow xml translation array value comparison with new 'equals_any_of' and 'equals_none_of' rules

---

app/javascript/hyacinth_ui_v1/components/controlled_vocabularies/ControlledVocabularyIndex.js
app/javascript/hyacinth_ui_v1/components/controlled_vocabularies/terms/TermIndex.js
app/javascript/hyacinth_ui_v1/components/ui/PaginationBar.js

This is enough to get controlled vocabularies working as expected. The PaginationBar component could probably use a refactor now that it's receiving different parameters. But I didn't want to focus on that just yet.

Moving vocabulary/terms ui queries to use limit/offset

---

Gemfile
app/graphql/hyacinth_schema.rb
config/routes.rb

Raise HyacinthSchema max_depth setting from 10 to 13 to accommodate GraphiQL interface needs; Enable GraphiQL interface for admins in non-development environments (but still always allow in development environment).

Enable GraphiQL interface for admins

---

app/graphql/mutations/digital_object/base_rights_mutation.rb
app/graphql/mutations/digital_object/update_asset_rights.rb
app/graphql/mutations/digital_object/update_item_rights.rb
app/graphql/types/digital_object/asset_rights_type.rb
app/graphql/types/digital_object/asset_type.rb
app/graphql/types/digital_object/base_rights.rb
app/graphql/types/digital_object/item_rights_type.rb
app/graphql/types/digital_object/item_type.rb
app/graphql/types/digital_object_interface.rb
app/graphql/types/mutation_type.rb
app/javascript/hyacinth_ui_v1/components/digital_objects/rights/rights_form/ItemRightsForm.js
lib/hyacinth/digital_object/rights_fields.rb
spec/factories/digital_objects/items.rb
spec/requests/graphql/mutations/digital_object/update_asset_rights_mutation_spec.rb
spec/requests/graphql/mutations/digital_object/update_item_rights_mutation_spec.rb
spec/requests/graphql/query/digital_object_spec.rb

- Generating GraphQL Types from mock dynamic fields hash.
- Added two mutations, one to update item rights and one to update asset rights

GraphQL Type for Rights and Rights Mutations

---

app/graphql/mutations/delete_dynamic_field.rb
app/graphql/mutations/delete_dynamic_field_group.rb
app/graphql/mutations/update_dynamic_field.rb
app/graphql/mutations/update_dynamic_field_group.rb
app/graphql/types/query_type.rb
app/javascript/hyacinth_v1/components/dynamic_fields/DynamicFieldIndex.js
spec/requests/graphql/mutations/delete_dynamic_field_group_spec.rb
spec/requests/graphql/mutations/delete_dynamic_field_spec.rb
spec/requests/graphql/mutations/update_dynamic_field_group_spec.rb
spec/requests/graphql/mutations/update_dynamic_field_spec.rb
spec/requests/graphql/query/dynamic_field_group_spec.rb
spec/requests/graphql/query/dynamic_field_spec.rb

I just realized that we can't use `string_key` as identifiers for dynamic field group and dynamic fields because `string_key`s for these two models aren't meant to be unique. The path for each field is unique. Therefore we can't use `string_keys` to do lookups.

Using id as identifier instead of string key for dynamic field groups and dynamic fields

---

app/graphql/mutations/field_export_profile/create_field_export_profile.rb
app/graphql/mutations/field_export_profile/delete_field_export_profile.rb
app/graphql/mutations/field_export_profile/update_field_export_profile.rb
app/graphql/types/mutation_type.rb
app/graphql/types/query_type.rb
app/javascript/hyacinth_v1/components/field_export_profiles/FieldExportProfileEdit.js
app/javascript/hyacinth_v1/components/field_export_profiles/FieldExportProfileForm.js
app/javascript/hyacinth_v1/components/field_export_profiles/FieldExportProfileIndex.js
app/javascript/hyacinth_v1/components/field_export_profiles/FieldExportProfileNew.js
app/javascript/hyacinth_v1/components/field_export_profiles/FieldExportProfiles.js
app/javascript/hyacinth_v1/graphql/fieldExportProfiles.js
spec/requests/graphql/mutations/field_export_profile/create_field_export_profile_spec.rb
spec/requests/graphql/mutations/field_export_profile/delete_field_export_profile_spec.rb
spec/requests/graphql/mutations/field_export_profile/update_field_export_profile_spec.rb
spec/requests/graphql/query/field_export_profile_spec.rb
spec/requests/graphql/query/field_export_profiles_spec.rb

Creating a graphql queries and mutation for field export profiles. Updating react components to query the graphql endpoint instead of the RESTful endpoint. 
Cannot remove RESTful endpoint until DynamicFieldGroupForm is converted to using the new graphql endpoint for FieldExportProfiles.
Closes HYACINTH-400.

Field export profiles migration

---

.rubocop_todo.yml
lib/tasks/hyacinth.rake
lib/tasks/hyacinth/development.rake

New development task (hyacinth:development:reset) clears all local data and sets up new basic setup data via hyacinth:setup:* tasks.
Also fixed purge_all_digital_objects task so that it no longer gets stuck on parent objects that have un-purged children.  Purge order doesn't matter when purging all objects.

Development environment reset task + updated reindex task

---

app/validators/string_key_validator.rb
spec/models/dynamic_field_group_spec.rb
spec/models/vocabulary_spec.rb
spec/validators/string_key_validator_spec.rb

String key validation now ensures that segments of letters and numbers are separated with one underscore. 
More details here: HYACINTH-614

Update to String Key Validation

---

app/javascript/hyacinth_v1/components/digital_objects/DigitalObjectInterface.js
app/javascript/hyacinth_v1/components/digital_objects/DigitalObjectList.js

2 related fixes here: a filter param formatting issue that triggered the ticketed JS error, and a change that suppresses search result paging in the digital object show footer when not applicable.

Hyacinth 682 js error navigating parent child

---

app/models/concerns/digital_object_concerns/attribute_assignment.rb
app/models/concerns/digital_object_concerns/attribute_assignment/preserve.rb
spec/models/concerns/digital_object_concerns/attribute_assignment/preserve_spec.rb

This change allows preservation_target_uris to be set as an attribute if they were previously unassigned, or ignored if they are identical. It raises AlreadySet if the new value and an existing non-empty value do not match.

preservation_target_uris is an assignable attribute (HYACINTH-603)

---

app/javascript/src/hyacinth_v1/utils/lazyFontAwesome.js

Declaring FontAwesomeIcon in component body reloads at runtime causing fallback to be used unnecessarily  (HYACINTH-883)

move lazy load of FontAwesomeIcon out of function body into module constant

---

spec/models/concerns/digital_object_concerns/attribute_assignment/doi_spec.rb

- update false pass for verifying ensure_doi called in save hook
- HYACINTH-393

refactor doi assignment concern's spec to clarify test cases

---

app/controllers/concerns/hyacinth/users/cas_authentication_behavior.rb
config/locales/devise.en.yml
lib/hyacinth/digital_object/resource_attributes.rb

Pulling this style conformance/message template work out of the HYACINTH-907 branch

use I18n for flash messages in Hyacinth::Users::CasAuthenticationBehavior

---

config/templates/solr_wrapper.template.yml

(for compatibility with Azul Zulu Java 8, which seems to have a smaller default value than other distributions)

HYACINTH-974: Specify -Xss1024k option for solr wrapper

---

.gitignore
Gemfile
lib/tasks/hyacinth/asset_zip.rake

Add hyacinth:asset_zip:from_hyacinth_csv_export rake task (with support for access, service, or master file export); Minor Gemfile edit to indicate that the rubyzip gem is now required for the project, and not just specified to ensure a minimum version for security reasons

HYACINTH-987: Add hyacinth:asset_zip:from_hyacinth_csv_export rake task

---

app/assets/javascripts/digital_objects_app/widgets/digital_object_editor.js
app/assets/javascripts/digital_objects_app/widgets/digital_object_search.js

Works in Chrome, makes hard refresh more effective in Firefox, does not change anything in Safari.

Attempt to invalidate cache after image rotation

---

app/assets/javascripts/digital_objects_app/models/digital_object/asset.js
app/assets/javascripts/digital_objects_app/models/digital_object/base.js
app/assets/javascripts/digital_objects_app/models/digital_object_search_result.js
app/assets/javascripts/digital_objects_app/widgets/digital_object_annotation_editor.js
app/assets/javascripts/digital_objects_app/widgets/digital_object_synchronized_transcript_editor.js
app/assets/templates/digital_objects_app/digital_objects/show.ejs
app/assets/templates/digital_objects_app/widgets/digital_object_editor/_header.ejs
app/controllers/assignments/changesets_controller.rb
app/controllers/assignments_controller.rb
app/controllers/digital_objects_controller.rb
app/models/digital_object/asset.rb
app/models/digital_object/base.rb
app/views/digital_objects/media_view.html.erb
spec/models/digital_object/asset_spec.rb

- consolidate tpye inspections behind methods on ruby and hs asset models

permit PCDM dc_type values for Assets if assigned (2.6.x)

---

app/assets/javascripts/digital_objects_app/models/digital_object/asset.js
app/assets/javascripts/digital_objects_app/models/digital_object/base.js
app/assets/javascripts/digital_objects_app/models/digital_object_search_result.js
app/assets/javascripts/digital_objects_app/widgets/digital_object_annotation_editor.js
app/assets/javascripts/digital_objects_app/widgets/digital_object_synchronized_transcript_editor.js
app/assets/templates/digital_objects_app/digital_objects/show.ejs
app/assets/templates/digital_objects_app/widgets/digital_object_editor/_header.ejs
app/controllers/assignments/changesets_controller.rb
app/controllers/assignments_controller.rb
app/controllers/digital_objects_controller.rb
app/models/digital_object/asset.rb
app/models/digital_object/base.rb
app/views/digital_objects/media_view.html.erb
spec/models/digital_object/asset_spec.rb

- consolidate tpye inspections behind methods on ruby and hs asset models

permit PCDM dc_type values for Assets if assigned (2.5.x)
